version: "3.8"
services:
  server:
    build: ./app/server/
    ports:
      - "5000:5000"
    volumes:
      - ./app/server:/app/
      - /app/node_modules
  client:
    build: ./app/client/
    ports:
      - "3000:3000"
    volumes:
      - ./app/client:/app/
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
