FROM node:lts as build

WORKDIR "/app"

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf *

COPY --from=build /app/build .

ENV PORT 3000

EXPOSE $PORT

ENTRYPOINT ["nginx", "-g", "daemon off;"]
